// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage/DarkHero.tsx": () => import("../components/mockups/homepage/DarkHero.tsx"),
  "./components/mockups/homepage/LightGrid.tsx": () => import("../components/mockups/homepage/LightGrid.tsx")
};
